resolver: lts-14.7
packages:
- '.'

# Only required for tests, and only for reporting test results in CI.
extra-deps:
- git: https://github.com/LeastAuthority/hspec-jenkins.git
  commit: 2899766bbd36216b81b1719423a5c2443458ae06
